# Generated by Django 5.0.8 on 2024-08-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsindexpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsindexpage',
            old_name='intro',
            new_name='name',
        ),
    ]
